### ISSUE TITLE
Does not function properly. Not sure how else to explain it, so here's a video. 

### ISSUE THREAD

**Issue by morgenman** [kanjieater/GoldenDict-Toolbelt#4]
`Error: Cannot write to packaged file at writeToSnapshot (pkg/prelude/bootstrap.js:571:16) 
at Object.fs.write (pkg/prelude/bootstrap.js:588:5) 
at writeAll (fs.js:1251:6) at writeFd (fs.js:1300:5) 
at fs.js:1291:7 
at zalgoSafe (pkg/prelude/bootstrap.js:256:10)
at pkg/prelude/bootstrap.js:472:9 
at FSReqWrap.oncomplete (fs.js:171:20)`

^^ this is the error that pops up before zen loads. If I swap the order, it doesn't show up. 

https://user-images.githubusercontent.com/3505950/125540616-1ac0655c-abee-4d26-9ffe-e76342ac827a.mp4

**Comment by kanjieater** [comment]
Hmm. Things definitely don't look right there. Do other dictionaries work fine? It looks like the styling isn't quite right either, which would lead me to believe some of the files aren't copied right. What version of goldendict is this?
